apiVersion: v1
kind: Pod
metadata: 
    name: backend-server
    labels:
        tier: backend
        app: goserver
spec:
    securityContext:
       seccompProfile:
         type: RuntimeDefault
    containers:
        - name: goserver
          #image: gcr.io/accurics/terrascan-e2e-test:terrascan@sha256:a7185142bbef5ccad92fc9bca0e09a522c2d163efcaa472fd31987d68ff9c61d
          #image: terrascan.azurecr.io/terrascan-e2e-test:nginx@sha256:3f13b4376446cf92b0cb9a5c46ba75d57c41f627c4edb8b635fa47386ea29e20
#           $$$$
          image: 245578940568.dkr.ecr.us-east-2.amazonaws.com/terrascan-e2e-test:terrascan
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true   
          resources:
            requests:
                cpu: "1"
                memory: "256Mi"
            limits:
                cpu: "1"
                memory: "256Mi"  
          # livenessProbe:
          #   exec:
          #   command:
          #   - go
          #   - version
          #   periodSeconds: 10
            # initialDelaySeconds: 10
          readinessProbe:
            exec:
            command:
            - go 
            - version
            periodSeconds: 10
            initialDelaySeconds: 10

    # initContainers:
    #   - name: initserver     
    #     image: terrascantest.azurecr.io/nginx
